#!/usr/bin/env bash
# This script tells a story based on the /etc/passwd file

# Read the /etc/passwd file line by line
while IFS=: read -r username password userid groupid description homedir shell
do
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $description"
done < /etc/passwd
