#!/usr/bin/env bash
# This script displays 'Best School' 10 times, but 'Hi' is added on the 9th iteration

i=1  # Initialize counter

# Start the while loop
while [ "$i" -le 10 ]
do
  if [ "$i" -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  i=$((i+1))  # Increment the counter
done
